// docs/design/issues-board/IssueBoard.jsx
// IssueBoard — kanban with 6 columns, scoped epic state, dim/filter modes
// Globals: IssueCard, STATUS_COLUMNS, ISSUE_TYPE_META

const { useState: useBoardState, useMemo: useBoardMemo } = React;

function ColumnHeader({ label, count, collapsed, onToggle, accent }) {
  return (
    <button
      onClick={onToggle}
      style={{
        display: "flex", alignItems: "center", gap: 8,
        padding: "10px 4px 10px 6px", width: "100%",
        background: "none", border: 0, cursor: "pointer",
        fontFamily: "inherit", color: "#94a3b8",
        borderBottom: `1px solid ${accent || "#1e293b"}`,
      }}
    >
      <span style={{
        width: 6, height: 6, borderRadius: 9999, background: accent || "#475569",
      }} />
      <span style={{
        fontSize: 11, fontWeight: 600, textTransform: "uppercase",
        letterSpacing: "0.05em", color: "#cbd5e1",
      }}>{label}</span>
      <span style={{
        fontSize: 10, fontWeight: 600, color: "#64748b",
        padding: "1px 6px", borderRadius: 9999,
        background: "rgb(51 65 85 / 0.4)",
        fontVariantNumeric: "tabular-nums",
      }}>{count}</span>
      <span style={{ marginLeft: "auto", fontSize: 10, color: "#64748b" }}>
        {collapsed ? "▸" : "▾"}
      </span>
    </button>
  );
}

const COLUMN_ACCENTS = {
  review:      "#a78bfa",
  todo:        "#64748b",
  in_progress: "#fcd34d",
  needs_help:  "#ef4444",
  done:        "#10b981",
  cancelled:   "#475569",
};

function FilterToolbar({
  search, setSearch,
  typeFilters, toggleType,
  blockedOnly, setBlockedOnly,
  showClosed, setShowClosed,
  scopedEpicId, scopedEpic, onClearScope,
  scopeMode, setScopeMode,
  totalCount, visibleCount,
}) {
  return (
    <div style={{
      display: "flex", flexDirection: "column", gap: 10,
      padding: "12px 16px", borderRadius: 8,
      background: "rgb(15 23 42 / 0.5)",
      border: "1px solid #1e293b",
      marginBottom: 16,
    }}>
      <div style={{ display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" }}>
        {/* Quiet search */}
        <div style={{
          display: "flex", alignItems: "center", gap: 6,
          padding: "5px 10px", borderRadius: 6,
          background: search ? "rgb(30 41 59 / 0.8)" : "rgb(15 23 42 / 0.4)",
          border: `1px solid ${search ? "#334155" : "transparent"}`,
          flex: "1 1 220px", minWidth: 180, maxWidth: 360,
          transition: "all 150ms",
        }}>
          <span style={{ fontSize: 11, color: "#475569" }}>⌕</span>
          <input
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            placeholder="Search id, title, description, comments…"
            style={{
              flex: 1, background: "transparent", border: 0, outline: "none",
              color: "#e2e8f0", fontSize: 12, fontFamily: "inherit",
            }}
          />
          {search && (
            <button onClick={() => setSearch("")} style={{
              background: "none", border: 0, color: "#64748b",
              cursor: "pointer", fontFamily: "inherit", fontSize: 12,
            }}>×</button>
          )}
        </div>

        {/* Type chips */}
        <div style={{ display: "flex", gap: 4 }}>
          {["epic", "bug", "feature"].map((t) => {
            const active = typeFilters.includes(t);
            const m = ISSUE_TYPE_META[t];
            return (
              <button key={t} onClick={() => toggleType(t)} style={{
                padding: "4px 10px", borderRadius: 9999, fontSize: 11, fontWeight: 600,
                color: active ? m.fg : "#94a3b8",
                background: active ? m.bg : "rgb(30 41 59 / 0.5)",
                border: `1px solid ${active ? m.border : "#334155"}`,
                cursor: "pointer", fontFamily: "inherit",
                textTransform: "capitalize", letterSpacing: "0.02em",
              }}>{m.label}</button>
            );
          })}
        </div>

        {/* Blocked toggle */}
        <button onClick={() => setBlockedOnly(!blockedOnly)} style={{
          padding: "4px 10px", borderRadius: 9999, fontSize: 11, fontWeight: 600,
          color: blockedOnly ? "#fca5a5" : "#94a3b8",
          background: blockedOnly ? "rgb(239 68 68 / 0.15)" : "rgb(30 41 59 / 0.5)",
          border: `1px solid ${blockedOnly ? "rgb(239 68 68 / 0.35)" : "#334155"}`,
          cursor: "pointer", fontFamily: "inherit",
        }}>⛔ Blocked only</button>

        {/* Closed toggle */}
        <label style={{ display: "inline-flex", alignItems: "center", gap: 6, fontSize: 11, color: "#94a3b8", cursor: "pointer" }}>
          <input
            type="checkbox"
            checked={showClosed}
            onChange={(e) => setShowClosed(e.target.checked)}
            style={{ accentColor: "#6366f1", cursor: "pointer" }}
          />
          Show closed
        </label>

        <span style={{ marginLeft: "auto", fontSize: 11, color: "#64748b" }}>
          {visibleCount} of {totalCount}
        </span>
      </div>

      {/* Active scope row */}
      {scopedEpicId && scopedEpic && (
        <div style={{
          display: "flex", alignItems: "center", gap: 8, padding: "6px 10px",
          borderRadius: 6, background: "rgb(99 102 241 / 0.1)",
          border: "1px solid rgb(99 102 241 / 0.3)",
        }}>
          <span style={{ fontSize: 11, fontWeight: 600, color: "#a5b4fc" }}>
            Scoped to epic
          </span>
          <span style={{ fontSize: 11, color: "#64748b", fontVariantNumeric: "tabular-nums" }}>
            {scopedEpicId}
          </span>
          <span style={{
            fontSize: 12, color: "#e2e8f0", flex: 1,
            overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap",
          }}>{scopedEpic.title}</span>
          <div style={{
            display: "inline-flex", borderRadius: 4, overflow: "hidden",
            border: "1px solid #334155",
          }}>
            {[
              { id: "filter",    label: "Filter" },
              { id: "highlight", label: "Highlight" },
            ].map((m) => (
              <button key={m.id} onClick={() => setScopeMode(m.id)} style={{
                padding: "3px 10px", fontSize: 10, fontWeight: 600,
                background: scopeMode === m.id ? "rgb(99 102 241 / 0.25)" : "transparent",
                color: scopeMode === m.id ? "#c7d2fe" : "#94a3b8",
                border: 0, cursor: "pointer", fontFamily: "inherit",
              }}>{m.label}</button>
            ))}
          </div>
          <button onClick={onClearScope} style={{
            padding: "2px 8px", fontSize: 11, fontWeight: 500, color: "#94a3b8",
            background: "rgb(30 41 59 / 0.5)", border: "1px solid #334155",
            borderRadius: 4, cursor: "pointer", fontFamily: "inherit",
          }}>Clear ×</button>
        </div>
      )}
    </div>
  );
}

function IssueBoard({ issues, repo, tweaks, onSelectIssue, scopedEpicId, setScopedEpicId }) {
  const [search, setSearch] = useBoardState("");
  const [typeFilters, setTypeFilters] = useBoardState([]);
  const [blockedOnly, setBlockedOnly] = useBoardState(false);
  const [showClosed, setShowClosed] = useBoardState(false);
  const [scopeMode, setScopeMode] = useBoardState("highlight");
  const [collapsed, setCollapsed] = useBoardState({ done: true, cancelled: true });

  const repoIssues = useBoardMemo(
    () => issues.filter((i) => i.repo === repo),
    [issues, repo]
  );

  const scopedEpic = useBoardMemo(
    () => scopedEpicId ? repoIssues.find((i) => i.id === scopedEpicId) : null,
    [scopedEpicId, repoIssues]
  );

  const isInScope = (i) => {
    if (!scopedEpicId) return true;
    return i.id === scopedEpicId || i.parent_id === scopedEpicId;
  };

  const baseFiltered = useBoardMemo(() => {
    return repoIssues.filter((i) => {
      if (typeFilters.length > 0 && !typeFilters.includes(i.type)) return false;
      if (blockedOnly && !i.blocked) return false;
      if (search) {
        const hay = (i.id + " " + i.title + " " + (i.description || "")).toLowerCase();
        if (!hay.includes(search.toLowerCase())) return false;
      }
      return true;
    });
  }, [repoIssues, typeFilters, blockedOnly, search]);

  const visible = useBoardMemo(() => {
    return baseFiltered.filter((i) => {
      // closed handling
      if (!showClosed && (i.status === "done" || i.status === "cancelled")) {
        // still show inside collapsed columns; column collapse handles render
      }
      // filter scope mode hides unrelated
      if (scopedEpicId && scopeMode === "filter" && !isInScope(i)) return false;
      return true;
    });
  }, [baseFiltered, scopedEpicId, scopeMode, showClosed]);

  const grouped = useBoardMemo(() => {
    const g = {};
    STATUS_COLUMNS.forEach((c) => g[c.id] = []);
    visible.forEach((i) => {
      if (g[i.status]) g[i.status].push(i);
    });
    // sort: epics first, then by updatedAt desc
    Object.keys(g).forEach((k) => {
      g[k].sort((a, b) => {
        if ((a.type === "epic") !== (b.type === "epic")) return a.type === "epic" ? -1 : 1;
        return b.updatedAt - a.updatedAt;
      });
    });
    return g;
  }, [visible]);

  const toggleType = (t) => setTypeFilters((prev) =>
    prev.includes(t) ? prev.filter((x) => x !== t) : [...prev, t]
  );

  const toggleCollapsed = (id) => setCollapsed((p) => ({ ...p, [id]: !p[id] }));

  const visibleColumns = STATUS_COLUMNS.filter((c) =>
    showClosed || (c.id !== "done" && c.id !== "cancelled") || grouped[c.id].length > 0
  );

  return (
    <div>
      <FilterToolbar
        search={search} setSearch={setSearch}
        typeFilters={typeFilters} toggleType={toggleType}
        blockedOnly={blockedOnly} setBlockedOnly={setBlockedOnly}
        showClosed={showClosed} setShowClosed={setShowClosed}
        scopedEpicId={scopedEpicId} scopedEpic={scopedEpic}
        onClearScope={() => setScopedEpicId(null)}
        scopeMode={scopeMode} setScopeMode={setScopeMode}
        totalCount={repoIssues.length} visibleCount={visible.length}
      />

      <div style={{
        display: "grid",
        gridTemplateColumns: visibleColumns.map((c) => collapsed[c.id] ? "minmax(180px, 1fr)" : "minmax(260px, 1fr)").join(" "),
        gap: 12, alignItems: "start",
        overflowX: "auto", paddingBottom: 8,
      }}>
        {visibleColumns.map((col) => {
          const isCollapsed = !!collapsed[col.id];
          const items = grouped[col.id] || [];
          return (
            <div key={col.id} style={{
              minWidth: isCollapsed ? 180 : 260,
              display: "flex", flexDirection: "column", gap: 8,
            }}>
              <ColumnHeader
                label={col.label}
                count={items.length}
                collapsed={isCollapsed}
                onToggle={() => toggleCollapsed(col.id)}
                accent={COLUMN_ACCENTS[col.id]}
              />
              {!isCollapsed && (
                <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                  {items.length === 0 ? (
                    <div style={{
                      padding: "20px 12px", textAlign: "center",
                      fontSize: 11, color: "#475569",
                      border: "1px dashed #1e293b", borderRadius: 8,
                    }}>No items</div>
                  ) : (
                    items.map((i) => (
                      <IssueCard
                        key={i.id}
                        issue={i}
                        onClick={() => onSelectIssue(i)}
                        dimmed={scopedEpicId && scopeMode === "highlight" && !isInScope(i)}
                        scoped={scopedEpicId && isInScope(i)}
                        onParentClick={(pid) => setScopedEpicId(pid)}
                      />
                    ))
                  )}
                </div>
              )}
              {isCollapsed && items.length > 0 && (
                <div style={{
                  padding: "8px 10px", fontSize: 11, color: "#64748b",
                  background: "rgb(15 23 42 / 0.4)", borderRadius: 6,
                  border: "1px solid #1e293b",
                }}>{items.length} hidden — click header to expand</div>
              )}
            </div>
          );
        })}
      </div>
    </div>
  );
}

Object.assign(window, { IssueBoard });

// dashboard/src/components/issues/IssueBoard.vue
<script setup lang="ts">
import { computed, ref, watch } from "vue";
import type { IssueListItem, IssueStatus } from "../../types";
import IssueCard from "./IssueCard.vue";
import { COLUMN_ACCENTS } from "./issuePalette";
import { isInScope, type ScopeMode } from "../../composables/useIssueFilters";

const props = defineProps<{
  issues: IssueListItem[];
  /**
   * When true, force-expands the Done + Cancelled columns regardless of
   * their default-collapsed setting. Cards in those columns are already
   * filtered out upstream when this is false, so the columns simply
   * render a 0 count + collapsed summary.
   */
  showClosed?: boolean;
  /**
   * When non-null, the board is scoped to an epic family. Out-of-scope
   * cards either dim (highlight mode) or are filtered upstream. The
   * board still receives the full list and applies the dim class via
   * the predicate; filter-mode exclusion happens in `IssuesPage`.
   */
  scopedEpicId: string | null;
  scopeMode: ScopeMode;
}>();

const emit = defineEmits<{
  select: [issue: IssueListItem];
  "parent-click": [parentId: string];
}>();

const COLUMN_ORDER: readonly IssueStatus[] = [
  "Review",
  "ToDo",
  "In Progress",
  "Needs Help",
  "Done",
  "Cancelled",
];

const collapsed = ref<Record<IssueStatus, boolean>>(
  COLUMN_ORDER.reduce(
    (acc, s) => { acc[s] = COLUMN_ACCENTS[s].collapsedByDefault; return acc; },
    {} as Record<IssueStatus, boolean>,
  ),
);

const grouped = computed<Record<IssueStatus, IssueListItem[]>>(() => {
  const g = COLUMN_ORDER.reduce(
    (acc, s) => { acc[s] = []; return acc; },
    {} as Record<IssueStatus, IssueListItem[]>,
  );
  for (const issue of props.issues) {
    const bucket = g[issue.status];
    if (!bucket) {
      // eslint-disable-next-line no-console
      console.warn(`IssueBoard: unknown issue status "${issue.status}" on ${issue.id}`);
      continue;
    }
    bucket.push(issue);
  }
  for (const status of Object.keys(g) as IssueStatus[]) {
    g[status].sort((a, b) => {
      if ((a.type === "Epic") !== (b.type === "Epic")) return a.type === "Epic" ? -1 : 1;
      return b.updated_at - a.updated_at;
    });
  }
  return g;
});

function dimmedFor(i: IssueListItem): boolean {
  return (
    !!props.scopedEpicId &&
    props.scopeMode === "highlight" &&
    !isInScope(i, props.scopedEpicId)
  );
}

function scopedFor(i: IssueListItem): boolean {
  return !!props.scopedEpicId && isInScope(i, props.scopedEpicId);
}

function toggle(status: IssueStatus): void {
  collapsed.value = { ...collapsed.value, [status]: !collapsed.value[status] };
}

// Show-closed = true force-expands Done + Cancelled. The off branch is a
// no-op: cards are already filtered out upstream, so the user's manual
// collapse state is preserved (and irrelevant to visibility).
watch(
  () => props.showClosed,
  (next) => {
    if (!next) return;
    collapsed.value = { ...collapsed.value, Done: false, Cancelled: false };
  },
  { immediate: true },
);
</script>

<template>
  <div class="board">
    <div
      v-for="status in COLUMN_ORDER"
      :key="status"
      class="column"
      :class="{ collapsed: collapsed[status] }"
    >
      <button
        class="header"
        type="button"
        :data-test="`column-header-${COLUMN_ACCENTS[status].id}`"
        :style="{ borderBottomColor: COLUMN_ACCENTS[status].accent }"
        @click="toggle(status)"
      >
        <span class="dot" :style="{ background: COLUMN_ACCENTS[status].accent }" />
        <span class="label">{{ COLUMN_ACCENTS[status].label }}</span>
        <span class="count">{{ grouped[status].length }}</span>
        <span class="glyph">{{ collapsed[status] ? "▸" : "▾" }}</span>
      </button>

      <div v-if="!collapsed[status]" class="cards">
        <div v-if="grouped[status].length === 0" class="empty">No items</div>
        <IssueCard
          v-for="issue in grouped[status]"
          :key="issue.id"
          :issue="issue"
          :dimmed="dimmedFor(issue)"
          :scoped="scopedFor(issue)"
          @select="(i) => emit('select', i)"
          @parent-click="(pid) => emit('parent-click', pid)"
        />
      </div>

      <div v-else-if="grouped[status].length > 0" class="collapsed-summary">
        {{ grouped[status].length }} hidden — click header to expand
      </div>
    </div>
  </div>
</template>

<style scoped>
.board {
  display: grid;
  grid-template-columns: repeat(6, minmax(260px, 1fr));
  gap: 12px;
  align-items: start;
  overflow-x: auto;
  padding-bottom: 8px;
}
.column {
  display: flex;
  flex-direction: column;
  gap: 8px;
  min-width: 260px;
}
.column.collapsed {
  min-width: 180px;
}
.header {
  display: flex;
  align-items: center;
  gap: 8px;
  padding: 10px 4px 10px 6px;
  width: 100%;
  background: none;
  border: 0;
  border-bottom: 1px solid #1e293b;
  cursor: pointer;
  font-family: inherit;
  color: #94a3b8;
}
.dot {
  width: 6px;
  height: 6px;
  border-radius: 9999px;
}
.label {
  font-size: 11px;
  font-weight: 600;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  color: #cbd5e1;
}
.count {
  font-size: 10px;
  font-weight: 600;
  color: #64748b;
  padding: 1px 6px;
  border-radius: 9999px;
  background: rgb(51 65 85 / 0.4);
  font-variant-numeric: tabular-nums;
}
.glyph {
  margin-left: auto;
  font-size: 10px;
  color: #64748b;
}
.cards {
  display: flex;
  flex-direction: column;
  gap: 8px;
}
.empty {
  padding: 20px 12px;
  text-align: center;
  font-size: 11px;
  color: #475569;
  border: 1px dashed #1e293b;
  border-radius: 8px;
}
.collapsed-summary {
  padding: 8px 10px;
  font-size: 11px;
  color: #64748b;
  background: rgb(15 23 42 / 0.4);
  border-radius: 6px;
  border: 1px solid #1e293b;
}
</style>
